### PR TITLE
blocks: add support for --read-percent

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/7)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocks/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbumS5oOgQSP9rxYGgq:-KbumS5oOgQSP9rxYGgr:b-2tjarh) ([raw file](https://github.com/cockroachdb/loadgen/blob/a8c6c9e38e2ec0714849bc62950982e14eb3ac35/blocks/main.go#L252)):*
> ```Go
> 		}
> 		return err
> 	}
> ```

@dt or @danhhz Is there a better way to do this query on Mongo? Apparently, it isn't kosher to use a random int as the `_id`, but perhaps I was just doing something wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocks/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbumS5oOgQSP9rxYGgq:-KbuqP4RyWxwaUWoXqwf:b-7w6gz2) ([raw file](https://github.com/cockroachdb/loadgen/blob/a8c6c9e38e2ec0714849bc62950982e14eb3ac35/blocks/main.go#L252)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@dt or @danhhz Is there a better way to do this query on Mongo? Apparently, it isn't kosher to use a random int as the `_id`, but perhaps I was just doing something wrong.
</blockquote></details>

Anything but arrays are allowed as `_id`. https://docs.mongodb.com/manual/core/document/#document-id-field

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocks/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbumS5oOgQSP9rxYGgq:-Kbv9XQpQiHwA60oU_ss:b-3r68i) ([raw file](https://github.com/cockroachdb/loadgen/blob/a8c6c9e38e2ec0714849bc62950982e14eb3ac35/blocks/main.go#L252)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Anything but arrays are allowed as `_id`. https://docs.mongodb.com/manual/core/document/#document-id-field
</blockquote></details>

Ok. Not sure what I was doing wrong before, but I've got this working now.

Btw, do I have to create an index on `_id`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocks/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbumS5oOgQSP9rxYGgq:-KbvApJdOlgG5cJ8P03X:brbsn0h) ([raw file](https://github.com/cockroachdb/loadgen/blob/a8c6c9e38e2ec0714849bc62950982e14eb3ac35/blocks/main.go#L252)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok. Not sure what I was doing wrong before, but I've got this working now.

Btw, do I have to create an index on `_id`?
</blockquote></details>

`_id` is the primary key (and so has an index). Something like `db.blocks.getIndexes()` from a mongo shell will tell you for sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7)*

**Comment by petermattis** [comment]
Can I get a review of this?

Btw, I think I'm going to rename this load generator to `kv` and simplify the schema. Objections?

**Comment by mberhault** [comment]
No objections to the rename.
It might be good to split the stats into read vs write though.

**Review by mberhault — APPROVED** [review]

**Review by bdarnell — APPROVED** [review]

**Comment by danhhz** [comment]
mongo part lgtm

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocks/main.go, line 292 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbzVSUQYhx0HUu5r5f5:-KbzVSURs8fbSPwhrWvt:b-e3t4l6) ([raw file](https://github.com/cockroachdb/loadgen/blob/b59e621712f395b519a4a7bce92d63a410b8b9f0/blocks/main.go#L292)):*
> ```Go
> 		return nil, err
> 	}
> 	if err := blocks.EnsureIndex(mgo.Index{Key: []string{"_id"}}); err != nil {
> ```

not strictly necessary, but doesn't really hurt anything

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-:-KbzVMbsrp-oyHZu7LEA:b-dqzlow)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocks/main.go, line 292 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/7#-KbzVSUQYhx0HUu5r5f5:-KbzYTeqEq0FS5OaAcuS:b8hkrhk) ([raw file](https://github.com/cockroachdb/loadgen/blob/b59e621712f395b519a4a7bce92d63a410b8b9f0/blocks/main.go#L292)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

not strictly necessary, but doesn't really hurt anything
</blockquote></details>

Yeah, I've removed this in a follow-on PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/7)*

**Pull request merged**
