### PR TITLE
Join on primary key for stock level query.

### PR DESCRIPTION
**Pull request by pbardea**
Increase ops/s for stock level from ~15 to ~180.

Edit: improvement is only up to ~25 ops/s

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM

image

**Comment by pbardea** [comment]
For future note: right now performance looks pretty similar regardless of which side filters the `w_id`, but there may be performance implications in the future if we do that filter on the `order_line` side or the `stock` side.

**Comment by rjnn** [comment]
I am so embarrassed for my detailed analysis of this query that completely missed this fact. Great find, @pbardea! :tada: :tada: :tada:

**Comment by pbardea** [comment]
Turns out that the local branch I was running of cockroach had a bug. The performance boost is very minor, but hopefully lookupJoins will speed it up some more.

**Comment by jordanlewis** [comment]
Swapping the order of the join operands seems to provide a small performance improvement as well, but I'm not sure if noise is affecting my measurements.

@arjunravinarayan can you provide some analysis on how operand order might affect this query?

**Comment by jordanlewis** [comment]
Hmm, I'm confused. The new plan claims to have a `mergeJoinOrder`, but distsql seems to plan it as a hash join anyway.

```
root@:26257/tpcc> explain select count(distinct(s_i_id)) from order_line join stock on s_i_id=ol_i_id and s_w_id=ol_w_id where ol_w_id=4 and ol_d_id=4 and ol_o_id between 40-20 and 40-1 and s_quantity < 50;
+---------------------+----------------+---------------------------------------+
|        Tree         |     Field      |              Description              |
+---------------------+----------------+---------------------------------------+
| group               |                |                                       |
|  └── render         |                |                                       |
|       └── join      |                |                                       |
|            │        | type           | inner                                 |
|            │        | equality       | (ol_i_id, ol_w_id) = (s_i_id, s_w_id) |
|            │        | mergeJoinOrder | +"(ol_w_id=s_w_id)"                   |
|            ├── scan |                |                                       |
|            │        | table          | order_line@primary                    |
|            │        | spans          | /4/4/39-/4/4/19                       |
|            └── scan |                |                                       |
|                     | table          | stock@primary                         |
|                     | spans          | /4-/5                                 |
+---------------------+----------------+---------------------------------------+
(12 rows)
```

And the corresponding `EXPLAIN(DISTSQL)` [output](https://cockroachdb.github.io/distsqlplan/decode.html?eJysks1q4zAQx-_7FGZOCejgj-QiWPCSZVn34JTUPbWmqNbUEXUkI42hJeTdi2VoGhOnBHrUSL_5f9h70EZiLnbogD9ABCWD1poKnTO2Hw0PMvkGPGSgdNtRPy4ZVMYi8D2QogaBQyGeG9ygkGiBgUQSqvFLW6t2wr6nxkq0T43SCAzWHfEgTVi6hPLAwHR03OxI1Ag8OrAfVHdkqldg8E81hLbXDh67MEyqYBlyzrO8-HQVsTRmaTJpLJ40dvTTaR8X5Ymbsie_e3Im3X_htjdG6XG4Bl9o1puN5r-tqrc08-bnx4InQyTXtPunri3WgsxIf7W-z4vZ3-yuyPJVEaTRfFJvcY3eBl1rtMNxeWc3h31jKGscvoAzna3w1prKywzHtef8QKKj4TYeDpn2V_53-wpHV8DxGI4vwskJHI7h5CK8GMHl4ddHAAAA__8MHjy1):

image

**Comment by rjnn** [comment]
You'll notice the `mergeJoinOrder` listed in the explain plan is a strict _prefix_ of the join columns. Thus, it cannot be used, unless we had a hybrid hash/merge physical processor, which we do not.

**Comment by jordanlewis** [comment]
Thanks - makes perfect sense.

**Comment by jordanlewis** [comment]
For the record, Postgres plans this query as a nested loop join:

```
tpcc=# explain select count(distinct(s_i_id)) from order_line join stock on s_i_id=ol_i_id and s_w_id=ol_w_id where ol_w_id=4 and ol_d_id=4 and ol_o_id between 40-20 and 40-1 and s_quantity < 50;
                                             QUERY PLAN
-----------------------------------------------------------------------------------------------------
 Aggregate  (cost=12.40..12.41 rows=1 width=8)
   ->  Nested Loop  (cost=0.84..12.40 rows=1 width=4)
         Join Filter: (order_line.ol_i_id = stock.s_i_id)
         ->  Index Scan using order_line_pkey on order_line  (cost=0.42..6.20 rows=1 width=8)
               Index Cond: ((ol_w_id = 4) AND (ol_d_id = 4) AND (ol_o_id >= 20) AND (ol_o_id <= 39))
         ->  Index Scan using stock_pkey on stock  (cost=0.42..6.19 rows=1 width=8)
               Index Cond: (s_w_id = 4)
               Filter: (s_quantity < 50)
(8 rows)
```

**Comment by rjnn** [comment]
To answer your previous question, operand order should not affect the execution cost AFAIK. Performing the filter on one side of the JOIN will almost certainly affect execution cost.

I also withdraw my previous embarrassment.

**Pull request merged**
