### PR TITLE
tpcc: implement data loader

### PR DESCRIPTION
**Pull request by jordanlewis**
Add implementation of the data load component of TPCC.

See http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-c_v5.11.0.pdf

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[tpcc/generate.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqoy-xHYVjQI4R1qYE1:-Kqoy-xHYVjQI4R1qYE2:b-vm05ve) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L30)):*
> ```Go
> )
> 
> // These constants are all sent by the spec - they're not knobs. Don't change
> ```

`s/sent/set/g`

---

*[tpcc/generate.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp054tp7T9TJkQsVS1:-Kqp054tp7T9TJkQsVS2:b3ontkk) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L58)):*
> ```Go
> 	stmts := strings.Split(string(data), ";")
> 	for _, stmt := range stmts {
> 		if err := crdb.ExecuteTx(db, func(tx *sql.Tx) error {
> ```

With only a single statement, there isn't much reason to be using a transaction vs executing the statement in an implicit transaction.

---

*[tpcc/generate.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqozFeckv1KlZFulnjP:-KqozFeckv1KlZFulnjQ:bkpwra5) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L75)):*
> ```Go
> }
> 
> func startWorkerPool(loader func(int), n int, entityName string) {
> ```

This name implies a function which returns a worker pool (to me, at least). But really what it is does run `loader` `n` times with `*concurrency` workers. Perhaps rename to `parallel` or something like that. Also, small nit: I think calling this function looks better if the function is last. Consider:

```
startWorkerPool(n, "foo", func(int) {
  // load the foos
})
```

vs 

```
startWorkerPool(func(int) {
  // load the foos
}, n "foo")
```

---

*[tpcc/generate.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqoxYPAowB5y9duCKz7:-KqoxYPAowB5y9duCKz8:by71607) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L99)):*
> ```Go
> 
> func generateData(db *sql.DB) {
> 	stmtItem := prepare(db, `INSERT INTO item (i_id, i_im_id, i_name, i_price, i_data) VALUES ($1, $2, $3, $4, $5)`)
> ```

I think you can use a little bit more formatting in these statements to make them more readable. For example:

```
stmtItem := prepare(db, `
INSERT INTO item (i_id, i_im_id, i_name, i_price, i_data) 
  VALUES ($1, $2, $3, $4, $5)
`)
```

---

*[tpcc/generate.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0iDQS-fyLYdcIktt:-Kqp0iDQS-fyLYdcIktu:b-g0fysu) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L139)):*
> ```Go
> 			ytd)
> 
> 		// 100,000 stock per warehouse..
> ```

`s/.././g`

---

*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-Kqp0YZUEm7VJHYcVsMZ:bvygl0f) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
> ```Go
> 		// 100,000 stock per warehouse..
> 		startWorkerPool(func(id int) {
> 			if _, err := stmtStock.Exec(id, w_id,
> ```

Does the spec say anything about how loading occurs? We'd likely see faster loading by batching inserts. If this is kosher, add a `TODO`.

---

*[tpcc/main.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp-NxF44ec805EKo3Y:-Kqp-NxF44ec805EKo3Z:bylh67) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/main.go#L44)):*
> ```Go
> func setupDatabase(dbURL string) (*sql.DB, error) {
> 	if *verbose {
> 		log.Printf("connecting to db: %s\n", dbURL)
> ```

IMO, `log.Printf` is overly verbose due to the prefixed timestamp info. For these load generators, I prefer `fmt.Printf` and including elapsed times when appropriate.

---

*[tpcc/random.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqmm0wiPtH9iUBpsISy:-Kqmm0wiPtH9iUBpsISz:b-kxwg2z) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L94)):*
> ```Go
> // randTax produces a random tax between [0.0000..0.2000]
> func randTax() float64 {
> 	return float64(randInt(0, 2000)) / float64(10000.0)
> ```

Is this specified? I would have though you'd do `rand.Float64() * 0.2`, though I guess that isn't inclusive at the end range.

---

*[tpcc/random.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqmmW0uqhCoEZiCcrN8:-KqmmW0uqhCoEZiCcrN9:b-3oao8v) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L99)):*
> ```Go
> // randInt returns a number within [min, max] inclusive.
> func randInt(min, max int) int {
> 	return rand.Intn(max-min) + min
> ```

Note that the global `rand` functions such as `rand.Intn` internally have a mutex. This actually shows up in profiling of load generators, so `kv` and `ycsb` use a per-goroutine random number generator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-:-Kqp12Yz84-sLPKSAro2:bnfp4nl)*

**Comment by rjnn** [comment]
:lgtm:, Major kudos for doing this so rapidly! Have you tested this out on a production cluster to see what sort of ops we get?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[tpcc/ddls.sql, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwxQtGQgBv0dGpMk2b:-KqwxQtGQgBv0dGpMk2c:b-w9hfmz) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/ddls.sql#L1)):*
> ```SQLPL
> create database if not exists tpcc;
> ```

You might want to gate this one on a flag (or just add a TODO), since its unsupported syntax in postgres. We do want to be able to run this load generator against postgres (eventually). 

---

*[tpcc/generate.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwydXjYPcylIkPChOX:-KqwydXjYPcylIkPChOY:b-4wc3rn) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L121)):*
> ```Go
> 	// 100,000 items.
> 	startWorkerPool(func(id int) {
> 		if _, err := stmtItem.Exec(id, randInt(1, 10000), randAString(14, 24), float64(randInt(100, 10000))/float64(100), randOriginalString()); err != nil {
> ```

Could use comments on the arguments the way you've done for the subsequent queries.

---

*[tpcc/generate.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwyoHwEgASUpvzXniP:-KqwyoHxw7Nhot1d2ZG9:bd2ulhc) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L178)):*
> ```Go
> 			// 3000 customers per district
> 			startWorkerPool(func(c_id int) {
> 				// 10% of the customer rows have bad credit.
> ```

This is a big ask to do now (so I don't ask for it), but in the future, when you get nuggets like this off the spec, can you link to the section or page number where the spec says this? When you write the comment you have the information at hand, now I'm searching to figure it out.

---

*[tpcc/main.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzYdszXAN0yrE9K9U:-KqwzYdszXAN0yrE9K9V:b4pkkbj) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/main.go#L67)):*
> ```Go
> 	}
> 
> 	dbURL := "postgresql://root@localhost:26257/tpcc?sslmode=disable"
> ```

Add a flag for `dbURL` since we'll use a proxy in the production clusters. This can be the default.

---

*[tpcc/random.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzkvzI0VXAfRqlv0z:-KqwzkvzI0VXAfRqlv1-:b-cyo3dh) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L28)):*
> ```Go
> 
> var cLastTokens = [...]string{
> 	"BAR", "OUGHT", "ABLE", "PRI", "PRES",
> ```

Is this seriously in the spec :roll_eyes: 

---

*[tpcc/random.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzqBtrhLWJlowc6N2:-KqwzqBtrhLWJlowc6N3:b-3b46dy) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L31)):*
> ```Go
> 	"ESE", "ANTI", "CALLY", "ATION", "EING"}
> 
> // cLoad is the value of C at load time. See 2.1.6.1.
> ```

Just calling out that this comment is exceptional. Makes it very easy to look up the relevant documentation. :ok_hand: :ok_hand: :ok_hand: 

---

*[tpcc/random.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqx-2TNO7AgwcIyF0fN:-Kqx-2TNO7AgwcIyF0fO:b-x4o9ds) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L40)):*
> ```Go
> }
> 
> func randFromAlphabet(min, max int, alphabet string) string {
> ```

Better named `randStringFromAlphabet`, and min and max are the lengths, so `minLen` and `maxLen`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-:-Kqx24RXYKmWisdZqei3:b-4wzuc7)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[tpcc/main.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzYdszXAN0yrE9K9U:-Kqx603zuadTpZeffz_k:b-147ym9) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/main.go#L67)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Add a flag for `dbURL` since we'll use a proxy in the production clusters. This can be the default.
</blockquote></details>

This is configurable via a command line argument, just as it is with `kv` and `ycsb`. See the following 2 lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by rjnn** [comment]
*[tpcc/main.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzYdszXAN0yrE9K9U:-Kqx8DGvIjDr1au1CwQ1:bg0tm9k) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/main.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is configurable via a command line argument, just as it is with `kv` and `ycsb`. See the following 2 lines.
</blockquote></details>

My bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by rjnn** [comment]
*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-Kqx9CwW9OsEhFHPY2U9:b-uy0pw6) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does the spec say anything about how loading occurs? We'd likely see faster loading by batching inserts. If this is kosher, add a `TODO`.
</blockquote></details>

I don't believe it does, from my reading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[tpcc/ddls.sql, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwxQtGQgBv0dGpMk2b:-Kqxu9YbeavyMoV7fzu0:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/ddls.sql#L1)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

You might want to gate this one on a flag (or just add a TODO), since its unsupported syntax in postgres. We do want to be able to run this load generator against postgres (eventually). 
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqoy-xHYVjQI4R1qYE1:-KqxuCByf8mlt8QyPMZ6:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L30)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/sent/set/g`
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp054tp7T9TJkQsVS1:-KqxuD0UXoY8hn8ti3NS:bnbumfo) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L58)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

With only a single statement, there isn't much reason to be using a transaction vs executing the statement in an implicit transaction.
</blockquote></details>

Can't you still get ambiguous commit errors with implicit transactions? This function protects against those.

---

*[tpcc/generate.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqozFeckv1KlZFulnjP:-Kqxu_QtkI3PWN-lr2Id:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L75)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This name implies a function which returns a worker pool (to me, at least). But really what it is does run `loader` `n` times with `*concurrency` workers. Perhaps rename to `parallel` or something like that. Also, small nit: I think calling this function looks better if the function is last. Consider:

```
startWorkerPool(n, "foo", func(int) {
  // load the foos
})
```

vs 

```
startWorkerPool(func(int) {
  // load the foos
}, n "foo")
```
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqoxYPAowB5y9duCKz7:-KqxvLNGoRTb5fjSLDU2:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you can use a little bit more formatting in these statements to make them more readable. For example:

```
stmtItem := prepare(db, `
INSERT INTO item (i_id, i_im_id, i_name, i_price, i_data) 
  VALUES ($1, $2, $3, $4, $5)
`)
```
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwydXjYPcylIkPChOX:-KqxwuDgFEJnrcCU-yTy:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L121)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Could use comments on the arguments the way you've done for the subsequent queries.
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0iDQS-fyLYdcIktt:-Kqxy8xOQm-uZc6A3lyV:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L139)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/.././g`
</blockquote></details>

Done.

---

*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-KqxyDpgnmhFHZoDt14-:b-1k8de4) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I don't believe it does, from my reading.
</blockquote></details>

No, the spec doesn't care about how the data is loaded. The speed of the data loading component is not part of the benchmark.

---

*[tpcc/generate.go, line 178 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwyoHwEgASUpvzXniP:-KqxyeA7fxfRBYzptTvc:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L178)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This is a big ask to do now (so I don't ask for it), but in the future, when you get nuggets like this off the spec, can you link to the section or page number where the spec says this? When you write the comment you have the information at hand, now I'm searching to figure it out.
</blockquote></details>

Done.

---

*[tpcc/main.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp-NxF44ec805EKo3Y:-KqxyhpmpjIerMqkUfSd:bhlyrh8) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/main.go#L44)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

IMO, `log.Printf` is overly verbose due to the prefixed timestamp info. For these load generators, I prefer `fmt.Printf` and including elapsed times when appropriate.
</blockquote></details>

This was cargo culted. Switched to fmt.

---

*[tpcc/random.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqwzkvzI0VXAfRqlv0z:-Kqxyqf8rUjKSqVzk-uk:b2ni4x7) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L28)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Is this seriously in the spec :roll_eyes: 
</blockquote></details>

ikr

---

*[tpcc/random.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqx-2TNO7AgwcIyF0fN:-Kqxz5w_8zgxH8v36kzH:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L40)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Better named `randStringFromAlphabet`, and min and max are the lengths, so `minLen` and `maxLen`.
</blockquote></details>

Done.

---

*[tpcc/random.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqmm0wiPtH9iUBpsISy:-KqxzO-sy6IaI-uNlJlz:by04ygm) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L94)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this specified? I would have though you'd do `rand.Float64() * 0.2`, though I guess that isn't inclusive at the end range.
</blockquote></details>

The spec says "W_TAX random within [0.0000 .. 0.2000]". Earlier, the spec defines a random range as:

```The term randomly selected within [x .. y] means independently selected at random and uniformly distributed between x and y, inclusively, with a mean of (x+y)/ 2, and with the same number of digits of precision as shown. For example, [0.01 .. 100.00] has 10,000 unique values, whereas [1 ..100] has only 100 unique values.```

This particular implementation is how the Java version I was looking at does it. Perhaps it's incorrect anyway because this really should be a precise decimal, but we're doing floating point arithmetic...
```


---

*[tpcc/random.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqmmW0uqhCoEZiCcrN8:-Kqy-ELgHODMRy79Ihtd:b-70kpcw) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L99)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Note that the global `rand` functions such as `rand.Intn` internally have a mutex. This actually shows up in profiling of load generators, so `kv` and `ycsb` use a per-goroutine random number generator.
</blockquote></details>

Noted. Once we get to the actual load generator I'll probably revisit this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*
<!-- Sent from Reviewable.io -->

**Comment by rjnn** [comment]
*[tpcc/random.go, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqmm0wiPtH9iUBpsISy:-Kqx-nMN9_xwe_bkaiTg:b-c6fc82) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/random.go#L94)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The spec says "W_TAX random within [0.0000 .. 0.2000]". Earlier, the spec defines a random range as:

```The term randomly selected within [x .. y] means independently selected at random and uniformly distributed between x and y, inclusively, with a mean of (x+y)/ 2, and with the same number of digits of precision as shown. For example, [0.01 .. 100.00] has 10,000 unique values, whereas [1 ..100] has only 100 unique values.```

This particular implementation is how the Java version I was looking at does it. Perhaps it's incorrect anyway because this really should be a precise decimal, but we're doing floating point arithmetic...
</blockquote></details>

`rand.Float64()` is bad because its not a uniform distribution and should generally be avoided (although due to the truncation to such a small number of significant digits should basically be fine here). I assume that's what the Java version is defensively programming against.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tpcc/generate.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp054tp7T9TJkQsVS1:-Kqy30EGUwVXqvvBfZ6i:b-edla84) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L58)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can't you still get ambiguous commit errors with implicit transactions? This function protects against those.
</blockquote></details>

`crdb.ExecuteTx` doesn't protect against ambiguous commit errors. Unless I'm missing something.

---

*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-KqyBlvRRt5c0uZWKgZS:bz6a6dx) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No, the spec doesn't care about how the data is loaded. The speed of the data loading component is not part of the benchmark.
</blockquote></details>

Let's add the `TODO`. The speed of loading can affect our dev cycle.

---

*[tpcc/generate.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-KqyBHMI07roCqa58dz0:-KqyBHMI07roCqa58dz1:bkq2uaf) ([raw file](https://github.com/cockroachdb/loadgen/blob/83385ba8acb5a91811f7691551c12f0e0f27109e/tpcc/generate.go#L101)):*
> ```Go
> 	stmtItem := prepare(db, `
> INSERT INTO item (i_id, i_im_id, i_name, i_price, i_data)
> VALUES ($1, $2, $3, $4, $5)`)
> ```

Nit: I think indentation of `VALUES` would help readability, though I suppose below you are placing `VALUES` in column 0 on purpose.  Meh, this isn't terribly important. The formatting is already much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by jordanlewis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[tpcc/generate.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp054tp7T9TJkQsVS1:-KqyD_rvHA02CZgbqSgv:b-kbe51q) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L58)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`crdb.ExecuteTx` doesn't protect against ambiguous commit errors. Unless I'm missing something.
</blockquote></details>

Err, yeah, you're right. Removed.

---

*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-KqyEF7TNR6IxzcEK-Tp:bn2ukpg) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's add the `TODO`. The speed of loading can affect our dev cycle.
</blockquote></details>

What kind of batching are you proposing here? Statement-level batching or unrolling into extra clauses in VALUES()? Added the TODO.

BTW, the loading is pretty slow - but not of stock or items. The slowest part is loading the orders, because of all of the FK validation that goes on.

That being said, loading a warehouse now takes about 2-3 minutes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tpcc/generate.go, line 141 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/63#-Kqp0YZUEm7VJHYcVsMY:-KqyF5gWV36PeFvyGIC5:b1nnqqx) ([raw file](https://github.com/cockroachdb/loadgen/blob/a4ffccb323d75ea822b144bdff5d78d4d838b952/tpcc/generate.go#L141)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What kind of batching are you proposing here? Statement-level batching or unrolling into extra clauses in VALUES()? Added the TODO.

BTW, the loading is pretty slow - but not of stock or items. The slowest part is loading the orders, because of all of the FK validation that goes on.

That being said, loading a warehouse now takes about 2-3 minutes.
</blockquote></details>

I'm proposing inserting multiple rows per INSERT statement. This should be done for all of the different types of INSERTs as it allows parallelization on the backend.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/63)*

**Pull request merged**
