### PR TITLE
kv: include flag values as subbench key-value pairs

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/main.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlYwUMwExNY7shanr0:-KrlYwUMwExNY7shanr1:b-7vpi0q) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L77)):*
> ```Go
> var sequential = flag.Bool("sequential", false, "Pick keys sequentially instead of randomly.")
> var drop = flag.Bool("drop", false, "Clear the existing data before starting.")
> var benchmarFileName = flag.String("benchmark-file", "-", "File name to write benchmark results to.")
> ```

`s/benchmarkFileName/benchmarkFileName/g`

---

*[kv/main.go, line 597 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlZBEsDX5nmyxOeYLh:-KrlZBEsDX5nmyxOeYLi:b-r6rrhq) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L597)):*
> ```Go
> 		defer func() {
> 			if err := f.Close(); err != nil {
> 				log.Fatalf("could not flush benchmark file %s: %s", *benchmarFileName, err)
> ```

`s/flush/close/g`

---

*[kv/main.go, line 603 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlYlqOY3ZpueYanlUn:-KrlYlqOY3ZpueYanlUo:b-xt7kds) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L603)):*
> ```Go
> 	}
> 
> 	dbURL := "postgres://root@localhost:26257/photos?sslmode=disable"
> ```

While you're here, can you `s/photos/test/g`.

---

*[kv/main.go, line 685 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlZayiSBMk0nMlJOE3:-KrlZayiSBMk0nMlJOE4:b-bslmxs) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L685)):*
> ```Go
> 		}, "/")
> 		// Output results that mimic Go's built-in benchmark format:
> 		// https://github.com/golang/go/blob/release-branch.go1.9/src/testing/benchmark.go#L335:L353
> ```

You can create a `testing.BenchmarkResult` manually and use `.String()` to format the output. This is fine as-is, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-:-KrlZyi2bW-zKRqTuuSp:bnfp4nl)*

**Comment by tamird** [comment]
Changed this to emit either benchmark-like output or tabular output. PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/main.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlYwUMwExNY7shanr0:-Krl_mCfGY9UQ8VsVGrb:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L77)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/benchmarkFileName/benchmarkFileName/g`
</blockquote></details>

Done.

---

*[kv/main.go, line 597 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlZBEsDX5nmyxOeYLh:-Krl_oSfrm94-VnAmHjN:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L597)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/flush/close/g`
</blockquote></details>

Done.

---

*[kv/main.go, line 603 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlYlqOY3ZpueYanlUn:-Krl_qTssyh7ImU5gEEd:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L603)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

While you're here, can you `s/photos/test/g`.
</blockquote></details>

Done.

---

*[kv/main.go, line 685 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-KrlZayiSBMk0nMlJOE3:-Krl_ruvABARcB1cZiGN:bo5nztk) ([raw file](https://github.com/cockroachdb/loadgen/blob/0c8dad2335d56d2869c117d650c4a47020e3f6cd/kv/main.go#L685)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can create a `testing.BenchmarkResult` manually and use `.String()` to format the output. This is fine as-is, though.
</blockquote></details>

Nice. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-:-KrleeyZaWViCCN94F9C:bd6rl90)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/71#-:-KrlfF5dxvMVTL2Zqwy0:bnfp4nl)*

**Comment by jordanlewis** [comment]
Might want to rebase this over the vendoring change, but LGTM otherwise

Actually it probably doesn't matter.

**Comment by tamird** [comment]
Done, thanks.

**Pull request merged**
