### PR TITLE
tpcc: fix up splitting and partitioning of the history table

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
Gah, meant to include this in the previous commit but forgot to push the changes.

**Comment by rjnn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tpcc/partition.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7ehjeE3F0NCgFCjXsc:-L7ehjeG8bi9dh4l8d7C:bhhbpap) ([raw file](https://github.com/cockroachdb/loadgen/blob/07da31ac371faca18ae2c84a8a0b4460bc8e81e2/tpcc/partition.go#L217)):*
> ```Go
> 
> func partitionHistory(db *sql.DB, wIDs []int, partitions int) {
> 	// NB: We use rand.Int63() to populate the history.rowid column. That
> ```

Obsolete comment.

---

*[tpcc/partition.go, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7eidKUfH5crSSVqvei:-L7eidKUfH5crSSVqvej:b-v37c1w) ([raw file](https://github.com/cockroachdb/loadgen/blob/07da31ac371faca18ae2c84a8a0b4460bc8e81e2/tpcc/partition.go#L222)):*
> ```Go
> 	rowids := make([]uuid.UUID, partitions+1)
> 	for i := 0; i < partitions; i++ {
> 		binary.BigEndian.PutUint64(rowids[i][:], uint64(i*(maxVal/partitions)))
> ```

This took me a while to understand, since you're leaving the second set of 8 bytes as zeros. Not sure there's anything actionable here as I can't come up with a helpful comment, but maybe one occurs to you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-:-L7eiwwEgzL33Fp6QGH4:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tpcc/partition.go, line 217 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7ehjeE3F0NCgFCjXsc:-L7ejHLQcShx6ZvL_4SM:bss4a2b) ([raw file](https://github.com/cockroachdb/loadgen/blob/07da31ac371faca18ae2c84a8a0b4460bc8e81e2/tpcc/partition.go#L217)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Obsolete comment.
</blockquote></details>

Removed.

---

*[tpcc/partition.go, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7eidKUfH5crSSVqvei:-L7ejI5OJD8PkIpCxZPH:b-b5o34y) ([raw file](https://github.com/cockroachdb/loadgen/blob/07da31ac371faca18ae2c84a8a0b4460bc8e81e2/tpcc/partition.go#L222)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This took me a while to understand, since you're leaving the second set of 8 bytes as zeros. Not sure there's anything actionable here as I can't come up with a helpful comment, but maybe one occurs to you?
</blockquote></details>

This is intentional. I'm trying to split the UUID key space evenly into N partitions. The partition column is sorted lexicographically, so I need to put partitioning values at the front of the UUID. I've added a comment to this effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/169)*

**Comment by rjnn** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tpcc/ddls.go, line 298 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7elmJZKG3SIARSMpJ-:-L7elmJZKG3SIARSMpJ0:b-ywd8ie) ([raw file](https://github.com/cockroachdb/loadgen/blob/6adca7edcb66aa78ed92c1d906671accd018ecfe/tpcc/ddls.go#L298)):*
> ```Go
> 
> 	// Split the history table into 1000 ranges.
> 	const maxVal = math.MaxUint64
> ```

Nice catch, I missed that.

---

*[tpcc/partition.go, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/169#-L7eidKUfH5crSSVqvei:-L7ekwpBqXtrBAJHm0hK:bgackty) ([raw file](https://github.com/cockroachdb/loadgen/blob/07da31ac371faca18ae2c84a8a0b4460bc8e81e2/tpcc/partition.go#L222)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is intentional. I'm trying to split the UUID key space evenly into N partitions. The partition column is sorted lexicographically, so I need to put partitioning values at the front of the UUID. I've added a comment to this effect.
</blockquote></details>

Yup, that's what took me a while to figure out. Very helpful comment, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/169)*

**Pull request merged**
