### PR TITLE
loadgen: add load generator that runs and profiles queries given

### PR DESCRIPTION
**Pull request by asubiotto**
Not sure about the name.

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not fond of the name. Perhaps `queryer` or something like that.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-:-KxrxLp87BMSF11VbtuH:bvbzwu)*

**Comment by RaduBerinde** [comment]
Name could also be `distsql`.


The query list LGTM.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[read/distsql-queries, line 9 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-Kxs0s8xaH5su-0H6uM1:-Kxs0s8xaH5su-0H6uM2:b-64f4l1) ([raw file](https://github.com/cockroachdb/loadgen/blob/c23d37ff1a1d1b6a2a0b3ed74304f389d97321ef/read/distsql-queries#L9)):*
> ```
> SELECT COUNT(DISTINCT l_suppkey) FROM tpch.lineitem LIMIT 1
> SELECT * FROM tpch.lineitem WHERE l_extendedprice < 1000
> SELECT * FROM tpch.lineitem JOIN supplier ON lineitem.l_suppkey = supplier.s_suppkey LIMIT 10
> ```

Not sure which of these might be a merge join, would be good to have both hashjoins and mergejoins

---

*[read/main.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-Kxs0HPuhxZj8rNH8_Dm:-Kxs0HPuhxZj8rNH8_Dn:b-z0hogn) ([raw file](https://github.com/cockroachdb/loadgen/blob/c23d37ff1a1d1b6a2a0b3ed74304f389d97321ef/read/main.go#L41)):*
> ```Go
> var distsql = flag.Bool("dist-sql", true, "Use DistSQL for query execution (this sets the cluster setting)")
> var loops = flag.Uint("loops", 0, "Number of times to run the queries (0 = run forever)")
> var maxLatency = flag.Duration("max-latency", 5*time.Minute, "Maximum time a query is expected to take (used as a histogram cutoff)")
> ```

[nit] confusing to see a `--max-latency X` flag, maybe name them `--histogram-max-latency` or `--histogram-min`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-:-Kxs0gvqXWKgx04xAZoD:b-86jbsw)*

**Comment by asubiotto** [comment]
Renamed to `querybench`. How does that sound?

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[read/distsql-queries, line 9 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-Kxs0s8xaH5su-0H6uM1:-KySQtJ-Yq3DX_bF0-N_:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c23d37ff1a1d1b6a2a0b3ed74304f389d97321ef/read/distsql-queries#L9)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure which of these might be a merge join, would be good to have both hashjoins and mergejoins
</blockquote></details>

Done.

---

*[read/main.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-Kxs0HPuhxZj8rNH8_Dm:-KySQtkIpOqyG3xmf3NY:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c23d37ff1a1d1b6a2a0b3ed74304f389d97321ef/read/main.go#L41)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] confusing to see a `--max-latency X` flag, maybe name them `--histogram-max-latency` or `--histogram-min`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-:-KySQlIYdFSPO2wJ9nrp:bao8erm)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/96#-:-KySV_8yn8tDDOowb5fj:bnfp4nl)*

**Pull request merged**
