### PR TITLE
rand: parameterize host, user, port

### PR DESCRIPTION
**Pull request by robert-s-lee**

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM after you run `gofmt` on the file - there are some mis-indented lines toward the bottom.

**Comment by robert-s-lee** [comment]
uploaded new commit with the format fix + new features.  Not sure how to perform the merge.

**Review by jordanlewis — APPROVED** [review]
LGTM, nice!

**Comment by jordanlewis** [comment]
You should be able to click `Merge pull request` on this page and that will merge the branch.

**Pull request merged**
