### PR TITLE
tpcc: option to modify transaction mix

### PR DESCRIPTION
**Pull request by jordanlewis**
This is useful for testing.

### CODE REVIEW

**Comment by rjnn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tpcc/main.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-Ks9ZnVIMybHpYBqDsY0:-Ks9ZnVIMybHpYBqDsY1:bqifqx) ([raw file](https://github.com/cockroachdb/loadgen/blob/771cf4627db188d6dbf3479cbf906eb5e1c50b90/tpcc/main.go#L46)):*
> ```Go
> var warehouses = flag.Int("warehouses", 1, "number of warehouses for loading")
> 
> var overrideMix = flag.String("override-mix", "", "Override transaction mix with a , delimited list of percentages")
> ```

Can state what the default mix is in the helper flag, which also gives you an opportunity to give an example of the format you're expecting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-:-Ks9ZwGp4BWEDnNuPBTz:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tpcc/main.go, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-Ks9ZnVIMybHpYBqDsY0:-Ks9kNnEJp7lw4S2mHrv:b79yk25) ([raw file](https://github.com/cockroachdb/loadgen/blob/771cf4627db188d6dbf3479cbf906eb5e1c50b90/tpcc/main.go#L46)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Can state what the default mix is in the helper flag, which also gives you an opportunity to give an example of the format you're expecting.
</blockquote></details>

Or make the default (the second parameter) contain the actual default mix. If that is done, I'd rename this flag to `mix`.

Nit: I find `a , delimited` difficult to read. Better to spell it out: `a comma delimited`.

---

*[tpcc/worker.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-Ks9kpkvfO1JyYyLmAhB:-Ks9kpkvfO1JyYyLmAhC:b-2g0bgw) ([raw file](https://github.com/cockroachdb/loadgen/blob/771cf4627db188d6dbf3479cbf906eb5e1c50b90/tpcc/worker.go#L100)):*
> ```Go
> 		if totalWeight != 100 {
> 			log.Fatalf("Invalid percentage mix %s: didn't add up to 100", percentStrs)
> 		}
> ```

I don't want to over-engineer this, but perhaps this should be `<txName>=<weight>`. For example, `tpmC=2,payment=0`. You're requiring the total weight to equal 100, but you could easily renormalize the weights. Not sure what will be more useful in practice. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-:-Ks9lKPtHz7wb5Kgl0Ye:bnfp4nl)*

**Comment by jordanlewis** [comment]
Thanks for the suggestions. I implemented your name/weight pair idea.

**Comment by petermattis** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/78#-:-Ks9xTkTONnS2qULgHCh:b-uwkowd)*

**Pull request merged**
