### PR TITLE
YCSB: implement incrementing Zipf distribution generator

### PR DESCRIPTION
**Pull request by rjnn**
This is a work in progress, I'm mostly interested in a review that checks if `zipfgenerator.go` correctly implements the algorithm from Page 24 of "Quickly Generating Billion-Record Synthetic Databases" (https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/syntheticdatagen.pdf). Actually integrating it properly into `main.go` is not yet complete.

There are some tests that help ensure some invariants, and that print out helpful distributions.

- [x] Implement the incrementing Zipf distribution random number generator
as specified by Gray et al (SIGMOD 1994). Use it in the key
generation step in the YCSB load generator.
- [x] Changing the YCSB load generator to use the incrementing
Zipf RNG.
- [x] verifying via a test that there are no read or write errors
(due to writing to a key that already has been written to, or reading
from a key that has not yet been written to) that result from running
the incrementing zipf generator.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/14)

### CODE REVIEW

**Comment by rjnn** [comment]
The YCSB load generator is done with this PR. Review of the Zipfian math assigned to @mjibson. cc @cuongdo and @petermattis if you're interested since you reviewed the previous PR.

Major change in `main.go` since the last PR: All the workers have to use a single shared Zipfian generator since a particular constant (`iMax`) must be shared and incremented under a lock to generate the write keys sequentially as per spec.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-:-KcJhjSjjCC_0cegtp0z:byv1orw)*

**Comment by madelynnblue** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[ycsb/zipfgenerator.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKBaxvyfdNdToiqO1i:-KcKBaxvyfdNdToiqO1j:bzbxs26) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L72)):*
> ```Go
> 	}
> 	if theta == 1.0 {
> 		return nil, errors.Errorf("theta cannot be exactly 1")
> ```

shouldn't we also check that theta < 1 and theta > 0?

---

*[ycsb/zipfgenerator.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKBpoveCC8_kPbENme:-KcKBpoveCC8_kPbENmf:b-g0eywy) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L89)):*
> ```Go
> 	// Compute hidden parameters
> 	var err error
> 	z.zeta2, err = computeZetaFromScratch(2, theta)
> ```

The paper says this is `zeta(theta, 2)`, not `zeta(2, theta)` as described here.

---

*[ycsb/zipfgenerator.go, line 93 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKB61ygaN3kjame3dU:-KcKB61ygaN3kjame3dV:b-wyhz2o) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L93)):*
> ```Go
> 		return nil, errors.Errorf("Could not compute zeta(2,theta): %s", err)
> 	}
> 	z.zeta, err = computeZetaFromScratch(iMax+1-iMin, theta)
> ```

Make some local variable `n` for this calculation since it's used a few times, and to be closer to the paper. Worth calling this `zetan` to be similar to the paper?

---

*[ycsb/zipfgenerator.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKEMYCLuIiA-M_3DGj:-KcKEMYD1SYbzZwsYBbl:bh98cco) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L121)):*
> ```Go
> 	var err error
> 	var zeta float64
> 	if zeta, err = computeZetaIncrementally(0, n, theta, 0.0); err != nil {
> ```

I would remove the two `var` lines and do `zeta, err := ...`, then the if on the next line. If you aren't using the if's scope, that is generally how it's done.

---

*[ycsb/zipfgenerator.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKFZD7qPu8iPp8g7iM:-KcKFZD9D-Ur_xBgzhLB:b195rag) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L139)):*
> ```Go
> 
> 	z.zipfGenMu.mu.Lock()
> 	defer z.zipfGenMu.mu.Unlock()
> ```

Avoid using a defer here since there's only one return path. defers are slow.

---

*[ycsb/zipfgenerator.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKFzs8KC-fDPukbL_L:-KcKFzs9msedv_tPAITn:bh3o6fy) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L146)):*
> ```Go
> 	}
> 	return result
> ```

remove empty line

---

*[ycsb/zipfgenerator.go, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGA3QMpFohAmIvJnA:-KcKGA3QMpFohAmIvJnB:bk4r16u) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L157)):*
> ```Go
> 
> 	var err error
> 	z.zeta, err = computeZetaIncrementally(z.zipfGenMu.iMax, z.zipfGenMu.iMax+1, z.theta, z.zeta)
> ```

Since we can return an error, avoid setting `z.zeta` here since it'll mess up the internal state of z. I'd do `zeta, err := ...`, check the error, then proceed changing internal state.

---

*[ycsb/zipfgenerator.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGQ2LQ_UcLHME051c:-KcKGQ2LQ_UcLHME051d:bskmvoe) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L158)):*
> ```Go
> 	var err error
> 	z.zeta, err = computeZetaIncrementally(z.zipfGenMu.iMax, z.zipfGenMu.iMax+1, z.theta, z.zeta)
> 	z.zipfGenMu.eta = (1 - math.Pow(2.0/float64(z.zipfGenMu.iMax+1-z.iMin), 1.0-z.theta)) / (1.0 - z.zeta2/z.zeta)
> ```

This should be after the error check.

---

*[ycsb/zipfgenerator.go, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGVnSeVDkQULItGWO:-KcKGVnT6TbC-bnnKhEd:bss704o) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L163)):*
> ```Go
> 	}
> 	z.zipfGenMu.iMax++
> 	return z.zipfGenMu.iMax - 1, nil
> ```

probably worth just copying the previous iMax instead of doing a subtraction immediately after the addition

---

*[ycsb/zipfgenerator.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGbYZYUL-7UxU8ZOe:-KcKGbYZYUL-7UxU8ZOf:birx4wv) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L166)):*
> ```Go
> }
> 
> func (z *ZipfGenerator) int() int {
> ```

This function seems pretty scary since it has the possibility of overflowing an int64. Is it used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/14)*

**Comment by rjnn** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[ycsb/zipfgenerator.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKBaxvyfdNdToiqO1i:-KcKShmRUUQPUxOywaly:b-7jz0tf) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L72)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

shouldn't we also check that theta < 1 and theta > 0?
</blockquote></details>

Theta can be greater than 1. But it must be greater than zero, so added that part.

---

*[ycsb/zipfgenerator.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKBpoveCC8_kPbENme:-KcKUVYZAcxpM35Y67Nj:b-m0cgpr) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L89)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The paper says this is `zeta(theta, 2)`, not `zeta(2, theta)` as described here.
</blockquote></details>

`n` is an int, and `theta` is a float, it doesn't make sense the other way around. I see what you're saying with the paper, it is confusing me as well now. See the YCSB code [here](https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/ZipfianGenerator.java#L140) as well.

---

*[ycsb/zipfgenerator.go, line 93 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKB61ygaN3kjame3dU:-KcKTDcbDCqAWAsO21y7:bvoyxkj) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L93)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Make some local variable `n` for this calculation since it's used a few times, and to be closer to the paper. Worth calling this `zetan` to be similar to the paper?
</blockquote></details>

Done on both counts.

---

*[ycsb/zipfgenerator.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKEMYCLuIiA-M_3DGj:-KcKTTUcNlrtb8kLEN0i:bqjnfuo) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L121)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I would remove the two `var` lines and do `zeta, err := ...`, then the if on the next line. If you aren't using the if's scope, that is generally how it's done.
</blockquote></details>

Doh, done.

---

*[ycsb/zipfgenerator.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKFZD7qPu8iPp8g7iM:-KcKT_2D9XQHTGRnEpTE:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L139)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Avoid using a defer here since there's only one return path. defers are slow.
</blockquote></details>

Done.

---

*[ycsb/zipfgenerator.go, line 146 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKFzs8KC-fDPukbL_L:-KcKTlXMkp0LiODjxnd8:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L146)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

---

*[ycsb/zipfgenerator.go, line 157 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGA3QMpFohAmIvJnA:-KcKTw9SA2A1gGrRsx29:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L157)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Since we can return an error, avoid setting `z.zeta` here since it'll mess up the internal state of z. I'd do `zeta, err := ...`, check the error, then proceed changing internal state.
</blockquote></details>

Done.

---

*[ycsb/zipfgenerator.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGQ2LQ_UcLHME051c:-KcKTz-XTvChFS2xkwLC:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L158)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This should be after the error check.
</blockquote></details>

Done.

---

*[ycsb/zipfgenerator.go, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGVnSeVDkQULItGWO:-KcKTzikXDOko2QHg4Tt:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L163)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

probably worth just copying the previous iMax instead of doing a subtraction immediately after the addition
</blockquote></details>

Done.

---

*[ycsb/zipfgenerator.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcKGbYZYUL-7UxU8ZOe:-KcKU4FTNY4G52fztUi3:b-9p1c0p) ([raw file](https://github.com/cockroachdb/loadgen/blob/c4bfe2bed966ea6fb54effb17e5f51026148205e/ycsb/zipfgenerator.go#L166)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This function seems pretty scary since it has the possibility of overflowing an int64. Is it used?
</blockquote></details>

Just used hackily in tests, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/14)*

**Comment by madelynnblue** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[ycsb/zipfgenerator.go, line 156 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-KcM2AntPTTabaPkUJUd:-KcM2AntPTTabaPkUJUe:bcuyl21) ([raw file](https://github.com/cockroachdb/loadgen/blob/f53b7320dc1ece8f9ffa2d72c4c7cce23433afa4/ycsb/zipfgenerator.go#L156)):*
> ```Go
> 	zetaN, err := computeZetaIncrementally(z.zipfGenMu.iMax, z.zipfGenMu.iMax+1, z.theta, z.zetaN)
> 	if err != nil {
> 		z.zipfGenMu.mu.Unlock()
> ```

I would use a defer in this case because of the multiple return paths. But if you are going for as fast as possible this is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-:-KcM2TXj9r-0zba2GtbS:bnfp4nl)*

**Comment by rjnn** [comment]
Thank you for the review!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/14#-:-KcNiKEUDxauU3qROgPV:b-rrkdbt)*

**Comment by cuongdo** [comment]
What's your plan for using this code now that it's done?

**Comment by rjnn** [comment]
It's currently deployed on denim, which wedged overnight after just 1.5 hours of load(!). I want to see this running continuously for a while on denim and get the kinks worked out (this week), and then run this nightly on terraform via TeamCity.

**Comment by cuongdo** [comment]
Great. Does this replace or supplement existing nightly load tests
(currently there's one for block_writer and another for photos)?

**Comment by rjnn** [comment]
We'll start with supplementing. We can always withdraw load tests as they are deemed redundant, but it's always good to have some period of overlapping statistics if we ever look back at the historical data and try and figure out what changed when.

**Pull request merged**
