### PR TITLE
Add the TPC-H data loader and benchmarker

### PR DESCRIPTION
**Pull request by rjnn**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/23)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 34 files reviewed at latest revision, 8 unresolved discussions.

---

*[tpch/.gitignore, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdX8RwpM5Qtekm7z0Wz:-KdX8RwpM5Qtekm7z0X-:b-t3h7ml) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/.gitignore#L3)):*
> ```
> tpch
> *.gz
> data/
> ```

Missing newline at the end of this file.

---

*[tpch/ddls.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXQFTecbQqGGqIvvnc:-KdXQFTfZgAB7Bq4yE9c:b-pb12du) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L43)):*
> ```Go
> )
> 
> var createStmts [numTables]string
> ```

You can initialize the create statements inline here. Also, this could be a slice and use the special slice-initialization syntax:

```
var createStmts = [...]string{
  nation: `
CREATE TABLE nation (...);
`,
  region: `
CREATE TABLE region (...);
`,
...
}
```

---

*[tpch/ddls.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPCVu_xMcpL_13zUr:-KdXPCVu_xMcpL_13zUs:blulsj) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L45)):*
> ```Go
> var createStmts [numTables]string
> var createIndexes = []string{
> 	"create unique index c_ck on customer (c_custkey asc)",
> ```

Capitalize the SQL keywords for consistency.

---

*[tpch/ddls.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXSEVjocQVEXjxHJnW:-KdXSEVjocQVEXjxHJnX:bh589yu) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L67)):*
> ```Go
> 	"create unique index n_nk on nation (n_nationkey asc)",
> 	"create index n_rk on nation (n_regionkey asc)",
> 	"create unique index r_rk on region (r_regionkey asc)",
> ```

Should these indexes be incorporated with the `CREATE TABLE` statements?

---

*[tpch/ddls.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPmEpARZQbsvM6ar-:-KdXPmEpARZQbsvM6ar0:b-p5h2ue) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L106)):*
> ```Go
> func createTablesAndIndexes(db *sql.DB) error {
> 	createStmts[nation] = `
> CREATE TABLE nation  ( n_nationkey  INTEGER NOT NULL,
> ```

We generally place the first column declaration on a new line.

---

*[tpch/ddls.go, line 239 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPjisv-lfCaoaN94w:-KdXPjisv-lfCaoaN94x:b77b2pj) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L239)):*
> ```Go
> 					indexStmt, err)
> 			}
> ```

Spurious newline.

---

*[tpch/query.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXU1Lg1pNX9SuuDujQ:-KdXU1LhrvAp8n1nciml:be5i3on) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/query.go#L28)):*
> ```Go
> func runQuery(db *sql.DB, query string) (int, error) {
> 	queryFilename := fmt.Sprintf("queries/query%s.sql", query)
> 	queryBytes, err := ioutil.ReadFile(queryFilename)
> ```

I think it would be better to bake the queries into the binary. Reading them from a file allows faster iteration on the queries, but requires the data files to be shipped with the binaries.

---

*[tpch/queries/query1.sql, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXUJ9QgpchjNBAx5Yi:-KdXUJ9QgpchjNBAx5Yj:b-nhdkvr) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/queries/query1.sql#L1)):*
> ```SQLPL
> select
> ```

Capitalize SQL keywords for consistency with our SQL style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/23)*

**Comment by rjnn** [comment]
Ready for another look.

Other change since previous commit: added a '-restore=/path/to/backup' flag.

---

Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[tpch/.gitignore, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdX8RwpM5Qtekm7z0Wz:-KdXick6C7lvvSkf-b4B:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/.gitignore#L3)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Missing newline at the end of this file.
</blockquote></details>

Done.

---

*[tpch/ddls.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXQFTecbQqGGqIvvnc:-KdarADDZ56VuDEKIfMb:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can initialize the create statements inline here. Also, this could be a slice and use the special slice-initialization syntax:

```
var createStmts = [...]string{
  nation: `
CREATE TABLE nation (...);
`,
  region: `
CREATE TABLE region (...);
`,
...
}
```
</blockquote></details>

Done.

---

*[tpch/ddls.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPCVu_xMcpL_13zUr:-KdahUiQf4M4U1E-dlpG:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Capitalize the SQL keywords for consistency.
</blockquote></details>

Done.

---

*[tpch/ddls.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXSEVjocQVEXjxHJnW:-KdarAp_llBPGuO4VWIw:boujui3) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should these indexes be incorporated with the `CREATE TABLE` statements?
</blockquote></details>

Yes. Done. In the far future we could load data, then create the indices, as Spanner does, but our asynchronous index addition performance is not great.

---

*[tpch/ddls.go, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPmEpARZQbsvM6ar-:-Kdai64AMpxyrtSSy1c4:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L106)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We generally place the first column declaration on a new line.
</blockquote></details>

Done.

---

*[tpch/ddls.go, line 239 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXPjisv-lfCaoaN94w:-KdXikmB2Kr4Lf84RBtM:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/ddls.go#L239)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Spurious newline.
</blockquote></details>

Done.

---

*[tpch/query.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXU1Lg1pNX9SuuDujQ:-KdbQY-hX2FnBK7VsxFK:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/query.go#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think it would be better to bake the queries into the binary. Reading them from a file allows faster iteration on the queries, but requires the data files to be shipped with the binaries.
</blockquote></details>

Done.

---

*[tpch/queries/query1.sql, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdXUJ9QgpchjNBAx5Yi:-KdazoU5Kly3TR0cgwM7:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/09a61dacb8a49c7bbcaceadb4616007cc7ab3014/tpch/queries/query1.sql#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Capitalize SQL keywords for consistency with our SQL style.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-:-KdbQZIb9NcLPd76jxBj:b-8gszhh)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[tpch/ddls.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdfBSiZOG8Aj8R0rTFN:-KdfBSiZOG8Aj8R0rTFO:b-om5xs0) ([raw file](https://github.com/cockroachdb/loadgen/blob/d2118e69cc9974072d4348b20dc63b99b6a4523a/tpch/ddls.go#L154)):*
> ```Go
> }
> 
> var dropStmts = []string{
> ```

It doesn't really matter, but you could `s/[]/[...]/g` for symmetry with `createStmts`.

---

*[tpch/query.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdfBiy3cqUOj6pKlx4W:-KdfBiy3cqUOj6pKlx4X:b-fsizht) ([raw file](https://github.com/cockroachdb/loadgen/blob/d2118e69cc9974072d4348b20dc63b99b6a4523a/tpch/query.go#L26)):*
> ```Go
> 
> var queryStmts = [...]string{
> 	1: `
> ```

This single slice is a bit overwhelming to read. How about a small reorganization: place each query in a file named after the query. For example, `query1.go` would contain:

```
const query1Stmt = `...`
```

And then this file would look like:

```
var queryStmts = [...]string{
  1: query1Stmt,
  2: query2Stmt,
  3: query3Stmt,
  ...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-:-KdfCFQ0p7LV-FvVKCzd:bnfp4nl)*

**Comment by rjnn** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[tpch/ddls.go, line 154 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdfBSiZOG8Aj8R0rTFN:-KdfhbqPxTKGRNZ8Suye:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/d2118e69cc9974072d4348b20dc63b99b6a4523a/tpch/ddls.go#L154)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It doesn't really matter, but you could `s/[]/[...]/g` for symmetry with `createStmts`.
</blockquote></details>

Done.

---

*[tpch/query.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/loadgen/23#-KdfBiy3cqUOj6pKlx4W:-KdfmSMN1_V57bGcf0FQ:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/d2118e69cc9974072d4348b20dc63b99b6a4523a/tpch/query.go#L26)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This single slice is a bit overwhelming to read. How about a small reorganization: place each query in a file named after the query. For example, `query1.go` would contain:

```
const query1Stmt = `...`
```

And then this file would look like:

```
var queryStmts = [...]string{
  1: query1Stmt,
  2: query2Stmt,
  3: query3Stmt,
  ...
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/23)*

**Pull request merged**
