### PR TITLE
kv: add a rate limiter to control the maximum op request frequency

### LINKED ISSUE #32: Add a %-utilization control to kv load-generator
Two possible mechanisms which come to mind are:
- A manual pause time between successive operations
- Run at full tilt for 30s to measure maximum throughput, and then add pauses to bring throughput to `x%` of the maximum.

### PR DESCRIPTION
**Pull request by spencerkimball**
Specify `--max-rate=<frequency>` in order to activate a rate limiter.

Fixes #32

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/33)

### CODE REVIEW

**Comment by spencerkimball** [comment]
+cc @BramGruneir

**Comment by BramGruneir** [comment]
LGTM

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/main.go, line 190 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/33#-KfHoMSigsbw_8H7JY05:-KfHoMSigsbw_8H7JY06:bxa43tn) ([raw file](https://github.com/cockroachdb/loadgen/blob/f37609a724a4870dd70e1f80b245d130df381199/kv/main.go#L190)):*
> ```Go
> 	if *maxRate > 0 {
> 		// Create a limiter using maxRate specified on the command line and
> 		// with allowed burst of 10s at the maximum allowed rate.
> ```

Where is the `allowed burst of 10s` happening? Looks like the burst size is 1.

---

*[kv/main.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/33#-KfHoqlkOIVfuV8PfT03:-KfHoqlkOIVfuV8PfT04:b-fr2snl) ([raw file](https://github.com/cockroachdb/loadgen/blob/f37609a724a4870dd70e1f80b245d130df381199/kv/main.go#L191)):*
> ```Go
> 		// Create a limiter using maxRate specified on the command line and
> 		// with allowed burst of 10s at the maximum allowed rate.
> 		b.limiter = rate.NewLimiter(rate.Limit(*maxRate), 1)
> ```

Don't you want to share a rate limiter amongst all of the `blockers`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/33#-:-KfHoj9NHh46nmji0d0m:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[kv/main.go, line 190 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/33#-KfHoMSigsbw_8H7JY05:-KfIXzzYnESQS6-NIVkp:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/f37609a724a4870dd70e1f80b245d130df381199/kv/main.go#L190)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Where is the `allowed burst of 10s` happening? Looks like the burst size is 1.
</blockquote></details>

Done.

---

*[kv/main.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/33#-KfHoqlkOIVfuV8PfT03:-KfIY-GT4PZIdcEOnkIv:b-896fix) ([raw file](https://github.com/cockroachdb/loadgen/blob/f37609a724a4870dd70e1f80b245d130df381199/kv/main.go#L191)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Don't you want to share a rate limiter amongst all of the `blockers`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/33)*

**Pull request merged**
