### PR TITLE
ycsb: specify full database.table

### PR DESCRIPTION
**Pull request by petermattis**
This avoids search path lookup and improves performance from 6,200
ops/sec to 14,700 ops/sec (130% !!!). Clearly we need to figure out why
the search path lookup is so costly.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/19)

### CODE REVIEW

**Comment by petermattis** [comment]
@knz, @nvanbenschoten I'm going to take a look at why the search-path lookup is so costly. Just a heads up in case you know of something.

**Comment by tamird** [comment]
LGTM (and wow)

**Review by a-robinson — APPROVED** [review]
WOW indeed

**Comment by petermattis** [comment]
The problem is in `planner.QualifyWithDatabase`. If you don't specify the database in the query, that method performs a call to `searchAndQualifyDatabase` which is apparently very slow. I'm speculating that it is performing extra KV reads instead of looking in the cached `SystemConfig`. Or something. Regardless, almost certainly fixable. 

```
func (p *planner) QualifyWithDatabase(t *parser.NormalizableTableName) (*parser.TableName, error) {
	tn, err := t.Normalize()
	if err != nil {
		return nil, err
	}
	if tn.DatabaseName == "" {
		if err := p.searchAndQualifyDatabase(tn); err != nil {
			return nil, err
		}
	}
	return tn, nil
}
```

**Review by rjnn — APPROVED** [review]
What!? How did you even find this? LGTM.

**Comment by petermattis** [comment]
> How did you even find this?

Profiling.

**Comment by rjnn** [comment]
Sounds like we might benefit from a lunch and learn on profiling! :)

**Pull request merged**
