### PR TITLE
Add build utils to loadgen repo.

### PR DESCRIPTION
**Pull request by mberhault**
This mimics the examples-go repo and is used by the teamcity project
https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Loadgen

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/loadgen/5)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[blocks/main.go, line 254 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqNzvSEMU3AmdmWlsx:-KbqNzvTfFY_7w4FgyV5:b-f2oiwe) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/blocks/main.go#L254)):*
> ```Go
> 
> 	var buf bytes.Buffer
> 	if _, err := buf.WriteString("BEGIN BATCH "); err != nil {
> ```

Eh, what is all this crap about? `buf.WriteString` won't error. Can we whitelist whatever check is complaining?

---

*[build/build-examples.sh, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOQZnbfVZin-FTodV:-KbqOQZnbfVZin-FTodW:b9sywzy) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/build-examples.sh#L2)):*
> ```Shell
> #!/bin/bash
> # Build the load generators.
> ```

Should the script be named `build-loadgen.sh`? Or just `build.sh`?

---

*[build/push-aws.sh, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOYHwb-7f4D8u2SkO:-KbqOYHwb-7f4D8u2SkP:bjxj7wf) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/push-aws.sh#L19)):*
> ```Shell
> LATEST_SUFFIX=".LATEST"
> REPO_NAME="loadgen"
> SHA="${CIRCLE_SHA1-$(git rev-parse HEAD)}"
> ```

Are we building this on CircleCI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5)*

**Comment by tamird** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[blocks/main.go, line 254 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqNzvSEMU3AmdmWlsx:-KbqPWHd9fJsv3CQTloC:bij1bgw) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/blocks/main.go#L254)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Eh, what is all this crap about? `buf.WriteString` won't error. Can we whitelist whatever check is complaining?
</blockquote></details>

Recent versions of errcheck won't complain about this, so idk what this is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5)*

**Comment by mberhault** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[blocks/main.go, line 254 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqNzvSEMU3AmdmWlsx:-KbqQuT7TaNnXXyGHOwv:b-1wmjc5) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/blocks/main.go#L254)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Recent versions of errcheck won't complain about this, so idk what this is.
</blockquote></details>

ah. right. nevermind then, reverting

---

*[build/build-examples.sh, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOQZnbfVZin-FTodV:-KbqSMpejzwguHaPPMX4:b-nwelyv) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/build-examples.sh#L2)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should the script be named `build-loadgen.sh`? Or just `build.sh`?
</blockquote></details>

changed to build.sh

---

*[build/push-aws.sh, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOYHwb-7f4D8u2SkO:-KbqSNs_oSRd7Z3oHslr:b-n321mp) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/push-aws.sh#L19)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are we building this on CircleCI?
</blockquote></details>

changed circleci mentions to teamcity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[build/push-aws.sh, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOYHwb-7f4D8u2SkO:-KbqTk6DTb9EycniGSnY:b5i9vb0) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/push-aws.sh#L19)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

changed circleci mentions to teamcity.
</blockquote></details>

This looks unchanged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-:-KbqTmAFPrwkBr75i_9Z:bnfp4nl)*

**Comment by mberhault** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[build/push-aws.sh, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOYHwb-7f4D8u2SkO:-KbqUVj2Wrj7H0s_7g82:b-9kyn6j) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/push-aws.sh#L19)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This looks unchanged.
</blockquote></details>

interesting. we seem to be using this everywhere. this means we just fall back on `git rev-parse HEAD`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5)*

**Comment by mberhault** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[build/push-aws.sh, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/loadgen/5#-KbqOYHwb-7f4D8u2SkO:-KbtuY8mdBMS-uvDpe4v:brpmqc3) ([raw file](https://github.com/cockroachdb/loadgen/blob/3c5968a0411edca1d341a053c45cc2affaa93543/build/push-aws.sh#L19)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

interesting. we seem to be using this everywhere. this means we just fall back on `git rev-parse HEAD`
</blockquote></details>

removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/5)*

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
