### PR TITLE
tpcc: batch all writes in delivery txn

### PR DESCRIPTION
**Pull request by nvb**
Alternative to #135.

This change replaces the for-each-district loop in the delivery
transaction with a series of batched statements that perform all
writes together. This reduces the number of round-trips required
by the transaction by an order of magnitude.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

On tpcc-200, this branch produced:

```
_elapsed______opName__ops(total)__ops/m(cum)__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.6s    newOrder      125460     25038.2     67.7     62.9     88.1    100.7    159.4   1610.6
  300.6s     payment      125716     25089.3     49.1     39.8     67.1     83.9    226.5   1677.7
  300.6s orderStatus       11760      2347.0     15.2     14.7     22.0     26.2     35.7    771.8
  300.6s    delivery       11856      2366.1     95.4     92.3    121.6    134.2    192.9   2013.3
  300.6s  stockLevel       11716      2338.2     71.7     67.1    125.8    151.0    192.9    352.3
```

For comparison, #135 produced:

```
_elapsed______opName__ops(total)__ops/m(cum)__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.6s    newOrder      124939     24937.0     82.2     75.5    117.4    142.6    209.7    906.0
  300.6s     payment      126116     25171.9     64.7     56.6    109.1    134.2    192.9    872.4
  300.6s orderStatus       11719      2339.0     16.2     15.2     25.2     29.4     39.8    125.8
  300.6s    delivery       11951      2385.3    502.4    469.8    671.1    838.9   1409.3   2281.7
  300.6s  stockLevel       11915      2378.2     55.7     48.2    104.9    125.8    176.2    385.9
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/loadgen/137#-:-L6bRxs4utZZf462jX-P:b-qe8nua)*

**Comment by jordanlewis** [comment]
The `pMax` of the other operations are worse on this branch than the other. I think this branch improves the `delivery` latency at the expense of other transactions. This intuitively makes sense, as a larger transaction will have more contention.

I think the other branch is likely still better. Minimizing `delivery` latency is unimportant - its 90%ile latency target is 80 seconds, and it can be queued for execution.

**Comment by petermattis** [comment]
@jordanlewis Batching also produced lower CPU usage and CPU seems to be one of our primary bottlenecks. #137 is on the left of the graph below and #135 is on the right:

screen shot 2018-03-02 at 10 55 31 am

**Comment by nvb** [comment]
> The pMax of the other operations are worse on this branch than the other. I think this branch improves the delivery latency at the expense of other transactions.

Doesn't the improvement in `p90/p95` latencies across all operations indicate the opposite? I don't really think `pMax` is what we should be comparing here.

**Pull request merged**
